# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 0 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  iptv:
    runs-on: ubuntu-latest
    steps:
      - name: Download & transform IPTV playlist
        uses: actions/checkout@v3
        run: bash ./script/generate_iptv.sh
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: iptv-archive
          path: ./iptv

  publish:
    runs-on: ubuntu-latest
    needs: [iptv]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
      - name: Publish to Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          folder: ./
          branch: gh-pages

